package Model;

import io.jboot.db.annotation.Table;
import Modelbase.BaseFile;

/**
 * Generated by Jboot.
 */
@Table(tableName = "file", primaryKey = "id")
public class File extends BaseFile<File> {
	
}
