package Model;

import io.jboot.db.annotation.Table;
import Modelbase.BaseTree;

/**
 * Generated by Jboot.
 */
@Table(tableName = "tree", primaryKey = "id")
public class Tree extends BaseTree<Tree> {
	
}
