package Model;

import io.jboot.db.annotation.Table;
import Modelbase.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {
	
}
